global: 
  external_labels: 
    monitor: test-monitor
  scrape_interval: 5s
scrape_configs: 
  - 
    job_name: prometheus
    static_configs: 
      - 
        targets: 
          - "157.245.203.125:9090"
  -
    job_name: node-exporter
    static_configs:
      -
        targets:
          - "node-exporter:9100"